// UI strings for Replay history, both languages side by side.
export const REPLAY_COPY = {
  en: {
    title: 'Replay history',
    subtitleCompany: 'Officers appointed and ceased over time',
    subtitleOfficer: 'Seats held and left over time',
    close: 'Close',
    loading: (loaded, total) => (total
      ? `Loading registry acts… ${loaded.toLocaleString('en-GB')} / ${total.toLocaleString('en-GB')}`
      : 'Loading registry acts…'),
    loadFailed: 'The registry history could not be loaded.',
    retry: 'Retry',
    empty: 'No appointments or cessations are recorded for this subject.',
    publicationDate: 'BORME publication date',
    play: 'Play',
    pause: 'Pause',
    nextAct: 'Next act',
    skipToEnd: 'Skip to end',
    speed: 'Speed',
    showPast: 'Show past seats',
    includeApoderados: 'Include apoderados',
    ledger: 'Registry acts',
    hideLedger: 'Hide acts',
    showLedger: 'Show acts',
    appointment: 'Appointment',
    cessation: 'Cessation',
    closure: 'Closed by dissolution, no published cessation',
    unknownStartRow: 'appointment not in the record',
    truncated: (date, missing) =>
      `Showing acts from ${date} onwards. ${missing.toLocaleString('en-GB')} earlier acts could not be loaded, so the first frames are incomplete.`,
    recordsBegin: date => `Records begin on ${date}: the subject existed before, so not everyone present in the first frame was appointed then.`,
    unknownStartNote: 'Dotted: a seat whose appointment predates the record.',
    inferredNote: 'Grey: a seat closed by dissolution or extinction, with no published cessation.',
    dense: n => `${n.toLocaleString('en-GB')} counterparts: labels appear on hover only.`,
    hiddenCount: n => `${n.toLocaleString('en-GB')} acts hidden (apoderados)`,
    legendAppointments: 'Appointments',
    legendCessations: 'Cessations',
    legendHidden: 'Hidden',
    actsCount: n => `${n.toLocaleString('en-GB')} acts`,
  },
  es: {
    title: 'Reproducir historia',
    subtitleCompany: 'Nombramientos y ceses a lo largo del tiempo',
    subtitleOfficer: 'Cargos ocupados y dejados a lo largo del tiempo',
    close: 'Cerrar',
    loading: (loaded, total) => (total
      ? `Cargando actos registrales… ${loaded.toLocaleString('es-ES')} / ${total.toLocaleString('es-ES')}`
      : 'Cargando actos registrales…'),
    loadFailed: 'No se ha podido cargar el historial registral.',
    retry: 'Reintentar',
    empty: 'No constan nombramientos ni ceses para este sujeto.',
    publicationDate: 'fecha de publicación en el BORME',
    play: 'Reproducir',
    pause: 'Pausa',
    nextAct: 'Siguiente acto',
    skipToEnd: 'Ir al final',
    speed: 'Velocidad',
    showPast: 'Mostrar cargos pasados',
    includeApoderados: 'Incluir apoderados',
    ledger: 'Actos registrales',
    hideLedger: 'Ocultar actos',
    showLedger: 'Ver actos',
    appointment: 'Nombramiento',
    cessation: 'Cese',
    closure: 'Cerrado por disolución, sin cese publicado',
    unknownStartRow: 'nombramiento fuera del registro',
    truncated: (date, missing) =>
      `Se muestran los actos desde el ${date}. No se han podido cargar ${missing.toLocaleString('es-ES')} actos anteriores, así que los primeros fotogramas están incompletos.`,
    recordsBegin: date => `El registro empieza el ${date}: el sujeto ya existía, así que no todos los presentes en el primer fotograma fueron nombrados entonces.`,
    unknownStartNote: 'Punteado: un cargo cuyo nombramiento es anterior al registro.',
    inferredNote: 'Gris: un cargo cerrado por disolución o extinción, sin cese publicado.',
    dense: n => `${n.toLocaleString('es-ES')} vínculos: los nombres solo aparecen al pasar el ratón.`,
    hiddenCount: n => `${n.toLocaleString('es-ES')} actos ocultos (apoderados)`,
    legendAppointments: 'Nombramientos',
    legendCessations: 'Ceses',
    legendHidden: 'Ocultos',
    actsCount: n => `${n.toLocaleString('es-ES')} actos`,
  },
};

export const replayCopyFor = language => REPLAY_COPY[language === 'en' ? 'en' : 'es'];
