/**
 * GENERATED by scripts/generate-registry-scale.mjs — do not edit by hand.
 *
 * Committed values are the build's fallback: if the stats endpoint is
 * unreachable at build time the site ships these rather than failing, so the
 * numbers can only ever be stale, never absent or wrong-by-typo.
 */
export const REGISTRY_SCALE_RAW = {
  totalCompanies: 3151041,
  totalEvents: 9584764,
  officerChanges: 6495011,
  constitutions: 1734504,
};
